from marshmallow import Schema, fields

class PropertySchema(Schema):
    # Numeric properties
    OverallQuall = fields.Float(required=True)
    YearBuilt = fields.Float(required=True)
    YearRemodAdd = fields.Float(required=True)
    MasVnrArea = fields.Float(required=True)
    BsmtFinSF1 = fields.Float(required=True)
    TotalBsmtSF = fields.Float(required=True)
    _1stFlrSF = fields.Float(required=True)
    GrLivArea = fields.Float(required=True)
    FullBath = fields.Float(required=True)
    HalfBath = fields.Float(required=True)
    TotRmsAbvGrd = fields.Float(required=True)
    Fireplaces = fields.Float(required=True)
    GarageYrBilt = fields.Float(required=True)
    GarageCars = fields.Float(required=True)
    GarageArea = fields.Float(required=True)
    WoodDeckSF = fields.Float(required=True)
    OpenPorchSF = fields.Float(required=True)

    # Categorized fields
    MSZoning = fields.Str(required=True)
    LotConfig = fields.Str(required=True)
    Neighborhood = fields.Str(required=True)
    Condition1 = fields.Str(required=True)
    Condition2 = fields.Str(required=True)
    BldgType = fields.Str(required=True)
    HouseStyle = fields.Str(required=True)
    RoofStyle = fields.Str(required=True)
    RoofMatl = fields.Str(required=True)
    Exterior1st = fields.Str(required=True)
    MasVnrType = fields.Str(required=True)
    ExterQual = fields.Str(required=True)
    BsmtQual = fields.Str(required=True)
    BsmtExposure = fields.Str(required=True)
    BsmtFinType1 = fields.Str(required=True)
    Heating = fields.Str(required=True)
    HeatingQC = fields.Str(required=True)
    CentralAir = fields.Str(required=True)
    KitchenQual = fields.Str(required=True)
    FireplaceQu = fields.Str(required=True)
    GarageCond = fields.Str(required=True)
    PoolQC = fields.Str(required=True)
    SaleCondition = fields.Str(required=True)
